---
- name: setup hex and rebar
  command: mix do local.hex --force, local.rebar --force
  args:
    chdir: "{{ansible_env['HOME']}}"
    creates: "{{ansible_env['HOME']}}/.mix/rebar"

- name: perform initial setup
  shell: |
    mix deps.get && \
    MIX_ENV=dev mix do compile, ecto.create, ecto.migrate && \
    MIX_ENV=test mix do compile, ecto.create, ecto.migrate
  args:
    chdir: /vagrant
    creates: /vagrant/_build

- name: ensure profile directory
  become: yes
  file:
    path: "/etc/profile.d"
    state: directory
    recurse: yes

- name: copy environment script
  become: yes
  template:
    src: etc/profile.d/kubera.sh.j2
    dest: /etc/profile.d/kubera.sh
    mode: 0755
