---
- name: ensure rabbitmq directory
  become: yes
  file:
    path: "/srv/rabbitmq"
    state: directory
    recurse: yes

- name: enable rabbitmq container
  become: yes
  docker_container:
    name: rabbitmq
    image: rabbitmq:3.6
    restart_policy: always
    volumes:
      - /srv/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
    env:
      RABBITMQ_DEFAULT_USER: "{{rabbitmq_user}}"
      RABBITMQ_DEFAULT_PASS: "{{rabbitmq_password}}"
      RABBITMQ_ERLANG_COOKIE: "{{rabbitmq_erlang_cookie}}"
